In [12]:
import numpy as np

# Initial weights and learning rate
W = np.array([10, 0.2, -0.75])
learning_rate = 0.05

# Training data for AND gate (inputs and corresponding target outputs)
X = np.array([[0, 0], [0, 1], [1, 0], [1, 1]])
Y = np.array([0, 0, 0, 1])

# Step activation function
def step_activation(x):
    return 1 if x >= 0 else 0

# Training the perceptron
def train_perceptron(X, Y, weights, learning_rate, epochs=100):
    for epoch in range(epochs):
        total_error = 0
        for i in range(len(X)):
            # Compute the predicted output
            predicted_output = step_activation(np.dot(X[i], weights))

            # Compute the error
            error = Y[i] - predicted_output
            total_error += error

            # Update weights
            weights += learning_rate * error * X[i]

        # Print the total error for this epoch
        print(f"Epoch {epoch+1}, Total Error: {total_error}")

        # If total error is 0, stop training as the perceptron has learned
        if total_error == 0:
            print("Perceptron has learned successfully.")
            break

# Train the perceptron
train_perceptron(X, Y, W, learning_rate)


ValueError: shapes (2,) and (3,) not aligned: 2 (dim 0) != 3 (dim 0)

In [2]:
# Bi-Polar Step activation function
def bipolar_step_activation(x):
    return 1 if x >= 0 else -1

# Modify the train_perceptron function to use bipolar step activation
def train_perceptron_bipolar(X, Y, weights, learning_rate, epochs=100):
    for epoch in range(epochs):
        total_error = 0
        for i in range(len(X)):
            # Compute the predicted output
            predicted_output = bipolar_step_activation(np.dot(X[i], weights))

            # Compute the error
            error = Y[i] - predicted_output
            total_error += error

            # Update weights
            weights += learning_rate * error * X[i]

        # Print the total error for this epoch
        print(f"Bipolar Step: Epoch {epoch+1}, Total Error: {total_error}")

        # If total error is 0, stop training as the perceptron has learned
        if total_error == 0:
            print("Perceptron has learned successfully.")
            break

# Train the perceptron with bipolar step activation
W_bipolar = np.array([10, 0.2, -0.75])  # Reset weights
train_perceptron_bipolar(X, Y, W_bipolar, learning_rate)


ValueError: shapes (2,) and (3,) not aligned: 2 (dim 0) != 3 (dim 0)

In [11]:
# Sigmoid activation function
def sigmoid_activation(x):
    return 1 / (1 + np.exp(-x))

# Modify the train_perceptron function to use sigmoid activation
def train_perceptron_sigmoid(X, Y, weights, learning_rate, epochs=100):
    for epoch in range(epochs):
        total_error = 0
        for i in range(len(X)):
            # Compute the predicted output
            predicted_output = sigmoid_activation(np.dot(X[i], weights))

            # Compute the error
            error = Y[i] - predicted_output
            total_error += error

            # Update weights
            weights += learning_rate * error * predicted_output * (1 - predicted_output) * X[i]

        # Print the total error for this epoch
        print(f"Sigmoid: Epoch {epoch+1}, Total Error: {total_error}")

        # If total error is 0, stop training as the perceptron has learned
        if total_error == 0:
            print("Perceptron has learned successfully.")
            break

# Train the perceptron with sigmoid activation
W_sigmoid = np.array([10, 0.2, -0.75])  # Reset weights
train_perceptron_sigmoid(X, Y, W_sigmoid, learning_rate)


ValueError: shapes (2,) and (3,) not aligned: 2 (dim 0) != 3 (dim 0)

In [4]:
# ReLU activation function
def relu_activation(x):
    return max(0, x)

# Modify the train_perceptron function to use ReLU activation
def train_perceptron_relu(X, Y, weights, learning_rate, epochs=100):
    for epoch in range(epochs):
        total_error = 0
        for i in range(len(X)):
            # Compute the predicted output
            predicted_output = relu_activation(np.dot(X[i], weights))

            # Compute the error
            error = Y[i] - predicted_output
            total_error += error

            # Update weights
            weights += learning_rate * error * (X[i] > 0).astype(int) * X[i]

        # Print the total error for this epoch
        print(f"ReLU: Epoch {epoch+1}, Total Error: {total_error}")

        # If total error is 0, stop training as the perceptron has learned
        if total_error == 0:
            print("Perceptron has learned successfully.")
            break

# Train the perceptron with ReLU activation
W_relu = np.array([10, 0.2, -0.75])  # Reset weights
train_perceptron_relu(X, Y, W_relu, learning_rate)


ValueError: shapes (2,) and (3,) not aligned: 2 (dim 0) != 3 (dim 0)

In [7]:
import numpy as np

# Sigmoid activation function and its derivative
def sigmoid(x):
    return 1 / (1 + np.exp(-x))

def sigmoid_derivative(x):
    return x * (1 - x)

# Input data (AND gate truth table)
X = np.array([[0, 0], [0, 1], [1, 0], [1, 1]])

# Target output for AND gate
Y = np.array([[0], [0], [0], [1]])

# Initialize weights and biases for the neural network
input_layer_neurons = X.shape[1]  # Number of features in the input layer
hidden_layer_neurons = 2  # Number of neurons in the hidden layer
output_neurons = 1  # Number of neurons in the output layer

# Initialize weights randomly with mean 0
weights_input_hidden = np.random.uniform(size=(input_layer_neurons, hidden_layer_neurons))
weights_hidden_output = np.random.uniform(size=(hidden_layer_neurons, output_neurons))

# Initialize biases randomly with mean 0
bias_hidden = np.random.uniform(size=(1, hidden_layer_neurons))
bias_output = np.random.uniform(size=(1, output_neurons))

# Learning rate
learning_rate = 0.5

# Number of epochs for training
epochs = 99924

# Training the neural network
for epoch in range(epochs):
    # Forward propagation
    hidden_layer_activation = np.dot(X, weights_input_hidden) + bias_hidden
    hidden_layer_output = sigmoid(hidden_layer_activation)

    output_layer_activation = np.dot(hidden_layer_output, weights_hidden_output) + bias_output
    predicted_output = sigmoid(output_layer_activation)

    # Compute error
    error = Y - predicted_output

    # Backpropagation
    d_predicted_output = error * sigmoid_derivative(predicted_output)
    error_hidden_layer = d_predicted_output.dot(weights_hidden_output.T)
    d_hidden_layer = error_hidden_layer * sigmoid_derivative(hidden_layer_output)

    # Update weights and biases
    weights_hidden_output += hidden_layer_output.T.dot(d_predicted_output) * learning_rate
    weights_input_hidden += X.T.dot(d_hidden_layer) * learning_rate

    bias_output += np.sum(d_predicted_output, axis=0, keepdims=True) * learning_rate
    bias_hidden += np.sum(d_hidden_layer, axis=0, keepdims=True) * learning_rate

# Print the final predicted output after training
print("Predicted output after training:")
print(predicted_output)

# Print the final weights and biases
print("\nFinal weights (input to hidden):")
print(weights_input_hidden)
print("\nFinal weights (hidden to output):")
print(weights_hidden_output)
print("\nFinal biases (hidden layer):")
print(bias_hidden)
print("\nFinal biases (output layer):")
print(bias_output)


Predicted output after training:
[[1.25629526e-04]
 [2.65003789e-03]
 [2.64612866e-03]
 [9.96140199e-01]]

Final weights (input to hidden):
[[ 3.09429056 -3.85970001]
 [ 3.14671546 -3.80385922]]

Final weights (hidden to output):
[[ 7.62082506]
 [-8.94190889]]

Final biases (hidden layer):
[[-4.35258434  5.46261929]]

Final biases (output layer):
[[-0.17477863]]


In [8]:
import numpy as np

# Sigmoid activation function and its derivative
def sigmoid(x):
    return 1 / (1 + np.exp(-x))

def sigmoid_derivative(x):
    return x * (1 - x)

# Input data (AND gate truth table)
X = np.array([[0, 0], [0, 1], [1, 0], [1, 1]])

# Target output for AND gate
Y = np.array([[1, 0], [1, 0], [1, 0], [0, 1]])

# Initialize weights and biases for the neural network
input_layer_neurons = X.shape[1]  # Number of features in the input layer
hidden_layer_neurons = 2  # Number of neurons in the hidden layer
output_neurons = 2  # Number of neurons in the output layer

# Initialize weights randomly with mean 0
weights_input_hidden = np.random.uniform(size=(input_layer_neurons, hidden_layer_neurons))
weights_hidden_output = np.random.uniform(size=(hidden_layer_neurons, output_neurons))

# Initialize biases randomly with mean 0
bias_hidden = np.random.uniform(size=(1, hidden_layer_neurons))
bias_output = np.random.uniform(size=(1, output_neurons))

# Learning rate
learning_rate = 0.05

# Number of epochs for training
epochs = 10000

# Training the neural network
for epoch in range(epochs):
    # Forward propagation
    hidden_layer_activation = np.dot(X, weights_input_hidden) + bias_hidden
    hidden_layer_output = sigmoid(hidden_layer_activation)

    output_layer_activation = np.dot(hidden_layer_output, weights_hidden_output) + bias_output
    predicted_output = sigmoid(output_layer_activation)

    # Compute error
    error = Y - predicted_output

    # Backpropagation
    d_predicted_output = error * sigmoid_derivative(predicted_output)
    error_hidden_layer = d_predicted_output.dot(weights_hidden_output.T)
    d_hidden_layer = error_hidden_layer * sigmoid_derivative(hidden_layer_output)

    # Update weights and biases
    weights_hidden_output += hidden_layer_output.T.dot(d_predicted_output) * learning_rate
    weights_input_hidden += X.T.dot(d_hidden_layer) * learning_rate

    bias_output += np.sum(d_predicted_output, axis=0, keepdims=True) * learning_rate
    bias_hidden += np.sum(d_hidden_layer, axis=0, keepdims=True) * learning_rate

# Print the final predicted output after training
print("Predicted output after training:")
print(predicted_output)

# Print the final weights and biases
print("\nFinal weights (input to hidden):")
print(weights_input_hidden)
print("\nFinal weights (hidden to output):")
print(weights_hidden_output)
print("\nFinal biases (hidden layer):")
print(bias_hidden)
print("\nFinal biases (output layer):")
print(bias_output)


Predicted output after training:
[[0.97782962 0.02166101]
 [0.95170664 0.04785997]
 [0.95158458 0.04791401]
 [0.06455137 0.93616374]]

Final weights (input to hidden):
[[0.44358127 4.28114815]
 [0.51178296 4.28427542]]

Final weights (hidden to output):
[[ 0.43581014 -0.30895423]
 [-7.21103466  7.22782352]]

Final biases (hidden layer):
[[ 0.81547294 -6.28188573]]

Final biases (output layer):
[[ 3.49797195 -3.60971129]]


In [9]:
import numpy as np

# Input data (AND gate truth table)
X = np.array([[0, 0], [0, 1], [1, 0], [1, 1]])

# Target output for AND gate
Y = np.array([[1, 0], [1, 0], [1, 0], [0, 1]])

# Calculate the pseudo-inverse of the input data
X_pseudo_inverse = np.linalg.pinv(X)

# Calculate the weights using the pseudo-inverse method
weights_pseudo_inverse = X_pseudo_inverse.dot(Y)

# Print the weights obtained using the pseudo-inverse method
print("Weights obtained using pseudo-inverse:")
print(weights_pseudo_inverse)

# Calculate predicted outputs using the weights obtained from the pseudo-inverse
predicted_output_pseudo_inverse = X.dot(weights_pseudo_inverse)

# Print the predicted outputs using the pseudo-inverse method
print("\nPredicted output using pseudo-inverse:")
print(predicted_output_pseudo_inverse)


Weights obtained using pseudo-inverse:
[[0.33333333 0.33333333]
 [0.33333333 0.33333333]]

Predicted output using pseudo-inverse:
[[0.         0.        ]
 [0.33333333 0.33333333]
 [0.33333333 0.33333333]
 [0.66666667 0.66666667]]


In [10]:
# Predicted outputs obtained from the perceptron learning approach
predicted_output_perceptron = predicted_output

# Compare the predicted outputs from both approaches
print("\nComparison of Predicted Outputs:")
print("Predicted output using perceptron learning:")
print(predicted_output_perceptron)
print("\nPredicted output using pseudo-inverse:")
print(predicted_output_pseudo_inverse)



Comparison of Predicted Outputs:
Predicted output using perceptron learning:
[[0.97782962 0.02166101]
 [0.95170664 0.04785997]
 [0.95158458 0.04791401]
 [0.06455137 0.93616374]]

Predicted output using pseudo-inverse:
[[0.         0.        ]
 [0.33333333 0.33333333]
 [0.33333333 0.33333333]
 [0.66666667 0.66666667]]


In [13]:
import numpy as np
import matplotlib.pyplot as plt

# Initial weights and training data for AND gate
W = np.array([10, 0.2, -0.75])
X = np.array([[0, 0], [0, 1], [1, 0], [1, 1]])
Y = np.array([0, 0, 0, 1])

# Step activation function
def step_activation(x):
    return 1 if x >= 0 else 0

# Training function to return the number of iterations for convergence
def train_perceptron(X, Y, weights, learning_rate, max_iterations=10000):
    iterations = 0
    for iteration in range(max_iterations):
        total_error = 0
        for i in range(len(X)):
            # Compute the predicted output
            predicted_output = step_activation(np.dot(X[i], weights))

            # Compute the error
            error = Y[i] - predicted_output
            total_error += error

            # Update weights
            weights += learning_rate * error * X[i]

        iterations += 1

        # If total error is 0, stop training as the perceptron has learned
        if total_error == 0:
            break

    return iterations

# Learning rates to test
learning_rates = [0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1.0]

# List to store the number of iterations for each learning rate
iterations_list = []

# Train the perceptron for each learning rate
for learning_rate in learning_rates:
    W = np.array([10, 0.2, -0.75])  # Reset weights
    iterations = train_perceptron(X, Y, W, learning_rate)
    iterations_list.append(iterations)

# Plotting the number of iterations vs. learning rates
plt.plot(learning_rates, iterations_list, marker='o')
plt.xlabel('Learning Rate')
plt.ylabel('Number of Iterations for Convergence')
plt.title('Number of Iterations vs. Learning Rate')
plt.grid(True)
plt.show()


ValueError: shapes (2,) and (3,) not aligned: 2 (dim 0) != 3 (dim 0)